-- CreateEnum
CREATE TYPE "LoanProductType" AS ENUM ('ASSET_BACKED', 'SALARY_BACKED', 'COLLATERAL', 'NON_COLLATERAL');

-- AlterTable
ALTER TABLE "Loan" ADD COLUMN IF NOT EXISTS "loanType" "LoanProductType" NOT NULL DEFAULT 'NON_COLLATERAL';
